{
  pkgs,
  lib,
  config,
  ...
}:

let
  # Zellij draws its own status bar and frames, so it ignores the OSC escapes
  # that recolour every other terminal program. It does watch its config file
  # and live-reloads a theme defined inline there — but only a real file: a
  # /nix/store symlink never changes, so nothing ever fires. Hence a generated
  # config, this file plus a theme block built from the palette the shell
  # publishes. The declarative source of truth is still ./config.kdl.
  themeSync = pkgs.writeShellScriptBin "zellij-theme-sync" ''
    set -eu

    out="$HOME/.config/zellij/config.kdl"
    colors="$HOME/.cache/wal/colors.sh"

    mkdir -p "$(dirname "$out")"

    {
      cat ${./config.kdl}

      if [ -r "$colors" ]; then
        . "$colors"
        # The legacy ten-colour theme format; zellij derives the rest from it.
        # The palette has no orange of its own, so yellow stands in.
        cat <<EOF

    themes {
        wal {
            fg "$foreground"
            bg "$background"
            black "$color0"
            red "$color1"
            green "$color2"
            yellow "$color3"
            blue "$color4"
            magenta "$color5"
            cyan "$color6"
            white "$color7"
            orange "$color3"
        }
    }
    theme "wal"
    EOF
      fi
    } > "$out.new"

    # Copied over rather than renamed: zellij watches the inode it opened, and
    # a rename would leave it watching the file we just replaced.
    cat "$out.new" > "$out"
    rm -f "$out.new"
  '';
in
{
  # home.packages = with pkgs; [
  #   fzf
  # ];

  # Was a store symlink; now generated by themeSync so zellij can reload it.
  # xdg.configFile."zellij/config.kdl".source = ./config.kdl;

  home.packages = [ themeSync ];

  home.activation.zellijTheme = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    run ${themeSync}/bin/zellij-theme-sync
  '';

  systemd.user.paths.zellij-theme = {
    Unit.Description = "Regenerate zellij's config when the published palette changes";
    Path.PathChanged = "%h/.cache/wal/colors.sh";
    Install.WantedBy = [ "paths.target" ];
  };

  systemd.user.services.zellij-theme = {
    Unit.Description = "Write zellij's config with the current palette";
    Service = {
      Type = "oneshot";
      ExecStart = "${themeSync}/bin/zellij-theme-sync";
    };
  };

  programs.zellij = {
    enable = true;
    enableFishIntegration = false;

    # attachExistingSession = true;

    exitShellOnExit = false;
    # themes = true;

    # Configuration written to
    # {file}$XDG_CONFIG_HOME/zellij/config.kdl.
    #
    # See <https://zellij.dev/documentation> for the full
    # list of options.
    # settings = builtins.readFile ./config.kdl;
  };
}
